### ISSUE TITLE
Reference of your implementation

### ISSUE THREAD

**Issue by rahmanidashti** [Mrdongsonny/POI-recommendation#1]
Hi, thanks for sharing.
It would be better if you write a good readme regarding the running of the source code. Also, please provide the reference of your source code if you have published it.

**Comment by whdong-whu** [comment]
OK,Thank you. I'll update it.

**Comment by rahmanidashti** [comment]
> OK,Thank you. I'll update it.

Thanks. Did you publish any paper? I am really keen to know your results and experiments.

**Comment by whdong-whu** [comment]
sorry,i don't publish paper,because it just  experimental research

**Comment by SeanLee2Cod** [comment]
> sorry,i don't publish paper,because it just experimental research

请问一下您的代码是对引用论文“RecNet: a deep neural network for personalized POI recommendation in location-based social networks”的完整实现吗？
