### ISSUE TITLE
hi~数据集在哪里下载

### ISSUE THREAD

**Issue by pkuwudi** [Mrdongsonny/POI-recommendation#3]
数据集在哪里下载。提到的论文有没有免费的链接。模型是否与用户的check-in时间有关，是做next poi的推荐吗

**Comment by whdong-whu** [comment]
您好，数据集我刚刚上传了，你可以参考下载

**Comment by Mrdongsonny** [comment]
> 数据集在哪里下载。提到的论文有没有免费的链接。模型是否与用户的check-in时间有关，是做next poi的推荐吗

**Comment by pkuwudi** [comment]
非常感谢您的回信
