### ISSUE TITLE
hi  请问代码里面的input.py里面的hecheng/u.txt和v.txt分别是什么数据集啊？ 

### ISSUE THREAD

**Issue by monkeyjingwen** [Mrdongsonny/POI-recommendation#4]
hi  请问代码里面的input.py里面的hecheng/u.txt和v.txt分别是什么数据集啊？

**Comment by whdong-whu** [comment]
主要是根据矩阵分解后得到的结果进行的合成，hecheng/u.txt和v.txt是原始数据进行矩阵分解和处理后的结果。实验的基本流程(细节请参照先关文献)是：首先将数据集内的数据进行归类和统计，然后进行矩阵分解，再进行整合，最后输入到网络框架中进行训练
