### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by monkeyjingwen** [Mrdongsonny/POI-recommendation#5]
这个代码是对RecNet这篇论文的实现吗？可是为什么代码写的是CNN，论文里面用的是DNN呢。还有代码的数据集不全，类别数据集没有，希望您可以补全数据集，并简单解释一下数据集。   我希望可以跟您交流，希望您留下自己的邮箱或者其他联系方式，多谢

**Comment by whdong-whu** [comment]
是使用的cnn进行的改进，数据集具体类别是后期需要统计和归类的，可以写一个简单脚本实现，具体类别也可以到数据集官网以爬虫或其他方式获取
